home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

popcorn_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages


# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

         {% comment %} <div id="navbar">
            <img id="logo" src="Logo\popcorn_logo_white_tranparan_2.png">
            <a href="#contact" class="menu" > Contact Us </a> &nbsp;
            <a href="#join" class="menu"> Join </a> &nbsp;
            <a href="#team" class="menu"> Team </a> &nbsp;
            <a href="#gallery" class="menu"> Gallery </a> &nbsp;
            <a href="about.html" class="menu"> About </a> &nbsp;
            <a href="index.html" class="menu"> Home </a> &nbsp;
         </div> {% endcomment %}
         
        <div id="about">
            <h4 id="about-text">ABOUT</h4> &nbsp;
            <img id="line-1" src="{% static 'home/images/line-1.png' %}">
            <h2 id="profil-kami">PROFIL KAMI</h2>
            <video id="comprof" src="{% static 'home/images/patrick-kelelahan.mp4' %}" controls autoplay loop muted></video>
            <h3 id="channel">Our Channel</h3>
            <p id="desc-video">Popcorn tersedia dalam channel YouTube. Kunjungi channel kami untuk mendapatkan terupdate seputar pornography.</p>
            <img id="lihat-button" src="{% static 'home/images/lihat-button.png' %}">
        </div>

{% endblock content %}

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% comment %} <script src="{% static 'home/js/script.js' %}"></script> {% endcomment %}
    <title>Popcorn!</title>
</head>
<body>
    <div id="navbar">
            <img id="logo" src="{% static 'home/images/popcorn_logo_white_tranparan_2.png' %}">
            <a href="#contact" class="menu" > Contact Us </a> &nbsp;
            <a href="#join" class="menu"> Join </a> &nbsp;
            <a href="#team" class="menu"> Team </a> &nbsp;
            <a href="#gallery" class="menu"> Gallery </a> &nbsp;
            <a href="{% url 'home:about' %}" class="menu"> About </a> &nbsp;
            <a href="{% url 'home:index' %}" class="menu"> Home </a> &nbsp;
         </div>
    {% block content%}
    
    {% endblock content%}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% comment %} <script src="{% static 'home/js/script.js' %}"></script> {% endcomment %}
    
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

         {% comment %} <div id="navbar">
            <img id="logo" src="{% static 'home/images/popcorn_logo_white_tranparan_2.png' %}">
            <a href="#contact" class="menu" > Contact Us </a> &nbsp;
            <a href="#join" class="menu"> Join </a> &nbsp;
            <a href="#team" class="menu"> Team </a> &nbsp;
            <a href="#gallery" class="menu"> Gallery </a> &nbsp;
            <a href="{% url 'home:About' %}" class="menu"> About </a> &nbsp;
            <a href="{% url 'home:index' %}" class="menu"> Home </a> &nbsp;
         </div> {% endcomment %}
         
        <div id="home">
             <h1>Welcome Fighters!</h1>
             <p id="desc">POPCORN (Protect Our Peers from Consuming Pornography) adalah komunitas anak muda yang concern dengan isu adiksi pornografi. POPCORN berfokus pada usaha preventif (berupa edukasi akan bahaya pornografi) maupun kuratif (berupa peer counseling).</p>
             <img id="fighters" src="{% static 'home/images/fighters.png' %}">
             <img id="get-started-button" src="{% static 'home/images/getStartedButton.png' %}">
        </div>

 {% endblock content %}